export const  CHANGE = 'CHANGE';
export const  REMAKE = 'REMAKE';
export const  SIGNED_IN = 'SIGNED_IN';
export const  SIGNED_OUT = 'SIGNED_OUT';
export const  CHANGE_LOADING_STATUS = 'CHANGE_LOADING_STATUS';
export const UPDATE_USER_LOCATION = 'UPDATE_USER_LOCATION';
export const UPDATE_TOKEN = 'UPDATE_TOKEN';
export const UPDATE_OFFICER_ID= 'UPDATE_OFFICER_ID';

