import {StyleSheet, Dimensions} from 'react-native';
import {Colors} from '../../styles/colors';
import {Fonts, Size} from '../../styles/fonts';

const ScreenSize  = Dimensions.get('window');
const styles = StyleSheet.create({
    container:{
        width:ScreenSize.width,
        height:ScreenSize.height,
        backgroundColor:Colors.BLACK,
    },
    headerContainer:{
        width:ScreenSize.width*0.9,
        alignSelf:'center',
        marginTop:20,
       flexDirection:'row',
       justifyContent:'center',
       marginLeft:10,
       height:200,
    },
    headerText:{
        fontFamily:Fonts.MonteSerratBold,
        fontSize:Size.HeaderSize,
        color:Colors.RED_LIGHT,
        marginTop:30
    },
    lottieContainerHeader:{
        width:200,
        height:200,
        marginLeft:20,
    },
    officerDetailContainer:{
        width:ScreenSize.width*0.9,
        alignSelf:"center",
        justifyContent:'flex-start',
        flexDirection:'row',
    },
    imageContainer:{
        width:100,
        height:100,
        borderRadius:50,
        justifyContent:'center',
        alignItems:'center',
        marginTop:20,
    },
    image:{
        width:100,
        height:100,
        borderRadius:50,
    },
    detailContainer:{
        justifyContent:'center',
        marginLeft:20,
    },
    nameText:{
        fontFamily:Fonts.OpenSans,
        fontSize:Size.ButtonText,
        color:Colors.WHITE,
    },
    officerCodeText:{
        fontFamily:Fonts.OpenSans,
        fontSize:Size.large,
        color:Colors.GRAY_MEDIUM,
    },
    lottieContainer:{
        flexDirection:'row',
        width:ScreenSize.width*0.9,
        height:100,
        alignItems:'center',
        marginVertical:10,
        borderBottomWidth:1,
        borderBottomColor:Colors.GRAY_EXTRA_DARK,
        marginHorizontal:20,
        elevation:2,
        alignSelf:'center',
        borderRadius:5,
        justifyContent:'space-between'
    },
    lottieText:{
        fontFamily:Fonts.MonteSerrat,
        fontSize:Size.ButtonText,
        marginLeft:20,
        color:Colors.WHITE,
        

    },
    lottieInnerContainer:{
        width:80,
        height:80,
        alignItems:'center',
        marginVertical:2,
        marginLeft:5
    
    },
    noteText:{
        fontFamily:Fonts.OpenSans,
        fontSize:Size.large,
        color:Colors.WHITE
    },
    noteContainer:{
        width:ScreenSize.width*0.8,
        alignSelf:'center',
        justifyContent:'center',
        backgroundColor:Colors.GRAY_DARK,
        borderRadius:20,
        marginVertical:10,
        padding:10
    },
    noAttachmentText:{
        fontFamily:Fonts.OpenSans,
        fontSize:Size.ButtonText,
        color:Colors.GRAY_MEDIUM,
    },
    noAttachmentTextContainer:{
        width:ScreenSize.width*0.9,
        alignSelf:'center',
        justifyContent:'center',
        marginTop:60,
    },
    backButtonContainer:{
        width:100,
        height:50,
    },
    addButtonContainer:{
        alignItems:'center',
        justifyContent:'space-between',
        marginLeft:20,
    },
    addText:{
        fontFamily:Fonts.MonteSerrat,
        fontSize:Size.small,
        color:Colors.WHITE,
    },
    mapContainer:{
        width:ScreenSize.width*0.9,
        alignSelf:'center',
        justifyContent:'center',
        alignItems:"center"
    },
    map:{
        width: ScreenSize.width * 0.9,
        height: ScreenSize.width * 0.8,
    },
    refreshContainer:{
        width:ScreenSize.width*0.9,
        alignItems:'flex-end',
    },
    policeIconContainer:{
        width:40,
        height:40,
        alignItems:'center',
        justifyContent:'center',
    },
    policeIcon:{
        width:40,
        height:40,
    },
    modal:{
        marginTop:ScreenSize.height*0.3,
        flex:1,
    },
    modalInnerContainer:{
        backgroundColor:Colors.BUTTON_DARK,
        height:200,
        borderRadius:20,
        
    },
    modalButtonsInnerContainer:{
        width:'100%',
        backgroundColor:Colors.BLACK,
        height:60,
        borderRadius:5,
        elevation:10,
        justifyContent:'center',
        alignItems:'center',
        marginTop:10,
        flexDirection:'row'
    },
    buttonTextInnerModal:{
        fontFamily:Fonts.OpenSansBold,
        color:Colors.RED_DARK,
        fontSize:Size.large,
    },
    modalCloseIconContainer:{
        width:'95%',
        height:40,
        justifyContent:'flex-end',
        alignItems:'flex-end',
    },
    modalButtonContainer:{
        justifyContent:'space-evenly',
        alignItems:'flex-start',
    },
    noteModalButtonContainer:{
        justifyContent:'space-evenly',
        alignItems:'flex-start',
        flexDirection:'row'
    },
    noteModalButtonsInnerContainer:{
        width:150,
        backgroundColor:Colors.GRAY_DARK,
        height:60,
        borderRadius:5,
        elevation:10,
        justifyContent:'center',
        alignItems:'center',
        marginTop:10,
        flexDirection:'row'
    },
    noteModalInnerContainer:{
        height:300,
        borderRadius:20,
        
    },
    noteInputTextContainer:{
        width:ScreenSize.width*0.8,
        padding:5,
        backgroundColor:Colors.WHITE,
        alignSelf:'center',
        alignItems:'flex-start',
        borderRadius:20,
        marginVertical:20,
    },
    input:{
        fontFamily:Fonts.OpenSans,
        fontSize:Size.large,
        color:Colors.GRAY_EXTRA_DARK,
    },
    noOnGoingComplaintContainer:{
        width:ScreenSize.width*0.9,
        alignSelf:'center',
        justifyContent:'center',
        alignItems:'center',
        padding:20,
        marginVertical:50,
    },
    noOnGoingText:{
        fontFamily:Fonts.MonteSerratSemiBold,
        fontSize:Size.ButtonText,
        color:Colors.WHITE,
    },
    subHeaderText:{
        marginTop:15, 
        fontFamily:Fonts.OpenSans,
        fontSize:Size.ButtonText,
        color:Colors.WHITE,
        marginLeft:10,
    },
    buttonContainer:{
        width:'100%',
        alignItems:'center',
        marginTop:40,
        marginBottom:20,
    },
    textInsideButtons:{
        fontFamily:Fonts.MonteSerratBold,
        fontSize:Size.ButtonText,
        color:Colors.RED_LIGHT
    },
    confirmText:{
        alignSelf:'center',
        color:Colors.RED_LIGHT,
        fontFamily:Fonts.OpenSansBold,
        fontSize:Size.ButtonText,
    },
    confirmModalButtonsInnerContainer:{
        width:'50%',
        backgroundColor:Colors.BLACK,
        height:60,
        borderRadius:5,
        elevation:10,
        justifyContent:'center',
        alignItems:'center',
        marginTop:10,
        flexDirection:'row',
        alignSelf:'center'
    },
    noOfficerContainer:{
        justifyContent:'center',
        marginLeft:20,
        marginVertical:10
    },
    noOfficerText:{
        fontFamily:Fonts.OpenSans,
        fontSize:Size.large,
        color:Colors.GRAY_MEDIUM,
    },
});
export default styles;